name: bpg_erp
description: A new Flutter project.
publish_to: "none" 

version: 1.0.0+2

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4
  share_plus: ^7.0.2
  image_cropper: ^5.0.0
  get: ^4.6.5
  google_mlkit_text_recognition: ^0.10.0
  shared_preferences: ^2.2.0
  qr_code_scanner: ^1.0.1
  flutter_dotenv: ^5.1.0
  dio: ^5.3.2
  flutter_spinkit: ^5.2.0
  http: ^1.1.0
  flutter_email_sender: ^6.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
    - .env.dev
    - .env.example